export const dummyProperties = [
  {
    id: "1",
    _id: "1",
    title: "Luxury 3BHK Apartment",
    description: "Beautiful 3BHK apartment in prime location with modern amenities.",
    price: 8500000,
    address: "123 Main Street",
    city: "Mumbai",
    state: "Maharashtra",
    zip_code: "400001",
    country: "India",
    property_type: "Flat",
    listing_type: "sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 1200,
    images: ["/assets/properties/flat-1.jpg", "/assets/properties/flat-2.jpg"],
    features: ["Swimming Pool", "Gym", "Parking"],
    latitude: 19.0760,
    longitude: 72.8777,
    views: 150,
    status: "approved",
    agent_id: "agent1",
    rooms: 3,
    floors: 1,
    furnishing: "Semi-Furnished",
    facing: "East",
    parking_spaces: 1,
    floor_plans: [],
    video_url: "",
    shops_count: 0,
    office_spaces: 0,
    age_of_property: "2 years",
    is_project: false,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z"
  },
  {
    id: "2",
    _id: "2",
    title: "Commercial Office Space",
    description: "Spacious office space perfect for startups and small businesses.",
    price: 15000000,
    address: "456 Business District",
    city: "Delhi",
    state: "Delhi",
    zip_code: "110001",
    country: "India",
    property_type: "Office Space",
    listing_type: "sale",
    bedrooms: 0,
    bathrooms: 2,
    area: 2000,
    images: ["/assets/properties/office-1.jpg", "/assets/properties/office-2.jpg"],
    features: ["Air Conditioning", "Security", "Elevator"],
    latitude: 28.7041,
    longitude: 77.1025,
    views: 200,
    status: "approved",
    agent_id: "agent2",
    rooms: 0,
    floors: 1,
    furnishing: "Fully Furnished",
    facing: "North",
    parking_spaces: 5,
    floor_plans: [],
    video_url: "",
    shops_count: 0,
    office_spaces: 1,
    age_of_property: "5 years",
    is_project: false,
    createdAt: "2024-01-02T00:00:00.000Z",
    updatedAt: "2024-01-02T00:00:00.000Z"
  },
  {
    id: "3",
    _id: "3",
    title: "Residential Plot",
    description: "Prime residential plot in a developing area.",
    price: 5000000,
    address: "789 Green Valley",
    city: "Bangalore",
    state: "Karnataka",
    zip_code: "560001",
    country: "India",
    property_type: "Plot",
    listing_type: "sale",
    bedrooms: 0,
    bathrooms: 0,
    area: 2400,
    images: ["/assets/properties/plot-1.jpg"],
    features: ["Corner Plot", "Gated Community"],
    latitude: 12.9716,
    longitude: 77.5946,
    views: 100,
    status: "approved",
    agent_id: "agent1",
    rooms: 0,
    floors: 0,
    furnishing: "",
    facing: "",
    parking_spaces: 0,
    floor_plans: [],
    video_url: "",
    shops_count: 0,
    office_spaces: 0,
    age_of_property: "",
    is_project: false,
    createdAt: "2024-01-03T00:00:00.000Z",
    updatedAt: "2024-01-03T00:00:00.000Z"
  },
  {
    id: "4",
    _id: "4",
    title: "Premium Project - Sky Towers",
    description: "Luxury residential project with world-class amenities.",
    price: 12000000,
    address: "101 Sky Towers",
    city: "Pune",
    state: "Maharashtra",
    zip_code: "411001",
    country: "India",
    property_type: "Flat",
    listing_type: "sale",
    bedrooms: 0,
    bathrooms: 0,
    area: 0,
    images: ["/assets/properties/flat-1.jpg"],
    features: ["Swimming Pool", "Gym", "Club House"],
    latitude: 18.5204,
    longitude: 73.8567,
    views: 300,
    status: "approved",
    agent_id: "agent2",
    rooms: 0,
    floors: 0,
    furnishing: "",
    facing: "",
    parking_spaces: 0,
    floor_plans: [],
    video_url: "",
    shops_count: 0,
    office_spaces: 0,
    age_of_property: "",
    is_project: true,
    project_name: "Sky Towers",
    total_towers: 3,
    total_units: 500,
    rera_number: "P52100012345",
    possession_date: "2026-12-31",
    construction_status: "Under Construction",
    unit_configurations: [
      { type: "2BHK", area_min: 800, area_max: 900, price_min: 8000000, price_max: 9000000 },
      { type: "3BHK", area_min: 1200, area_max: 1400, price_min: 12000000, price_max: 14000000 }
    ],
    connectivity: [
      { type: "Airport", name: "Pune Airport", distance: "15 km" },
      { type: "Railway Station", name: "Pune Railway Station", distance: "10 km" }
    ],
    nearby_places: [
      { type: "Mall", name: "Phoenix Mall", distance: "2 km" },
      { type: "Hospital", name: "Ruby Hall Clinic", distance: "3 km" }
    ],
    project_highlights: ["Gated Community", "24/7 Security", "Power Backup"],
    createdAt: "2024-01-04T00:00:00.000Z",
    updatedAt: "2024-01-04T00:00:00.000Z"
  }
];

export const dummyUsers = [
  {
    id: "agent1",
    _id: "agent1",
    uuid: "agent1-uuid",
    email: "agent1@example.com",
    full_name: "John Doe",
    phone: "+91-9876543210",
    role: "agent",
    avatar_url: "/assets/avatars/agent1.jpg",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z"
  },
  {
    id: "agent2",
    _id: "agent2",
    uuid: "agent2-uuid",
    email: "agent2@example.com",
    full_name: "Jane Smith",
    phone: "+91-9876543211",
    role: "agent",
    avatar_url: "/assets/avatars/agent2.jpg",
    createdAt: "2024-01-02T00:00:00.000Z",
    updatedAt: "2024-01-02T00:00:00.000Z"
  },
  {
    id: "admin1",
    _id: "admin1",
    uuid: "admin1-uuid",
    email: "admin@example.com",
    full_name: "Admin User",
    phone: "+91-9876543212",
    role: "admin",
    avatar_url: "/assets/avatars/admin.jpg",
    createdAt: "2024-01-03T00:00:00.000Z",
    updatedAt: "2024-01-03T00:00:00.000Z"
  }
];